### ISSUE TITLE
Update to python 3.11.3

### ISSUE THREAD

**Issue by lk16** [lk16/aaa#69]
Update the following files:
- `pyproject.toml`
- `.github/workflows/workflow.yml`
- `README.md`

To confirm all changes are done, the following command should output nothing:
```sh
git grep -l '3\.10' | grep -v pdm.lock
```

**Comment by LirakR** [comment]
While working on the ticket I found a few stuff that are out of the scope of this ticket but I think they need to be fixed:
- The `.pdm-python` should be added to gitignore since it is generated by the `pdm install` command
- The file `.github/workflows/workflow.yml` needs to have a value for the `version` argument at line 19.
